# name: "ğŸš€ release"

# on:
#   push:
#     branches:
#       - "master"

# jobs:
#   release:
#     name: ğŸš€ release
#     runs-on: ubuntu-latest
#     steps:
#       - name: ğŸ“š checkout
#         uses: actions/checkout@v2
#       - name: ğŸŸ¢ node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org
#       - name: ğŸš€ publish
#         run: npm publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
